### PR TITLE
User level based permissions

### LINKED ISSUE #63: User based permission
Hello,

Currently you have a role based permission but it can be useful to have (in addition to role based permission) a User based permission.

I will try to explain, I have : 
Model A
User A
User B

User A has created a record of Model A, however, User A does not want the User B (and only him) have access to that record.

Can I do this actually with sails-permissions ?

Thanks in advance for your response.

### PR DESCRIPTION
**Pull request by anthonybriand**
I implemented the user-level permission, thank you to look and let me know if you agree my implementation.

- resolves #63

### CODE REVIEW

**Comment by tjwebb** [comment]
@anthonybriand wow that was fast! Thanks for the PR and the tests. We'll review it and merge it in.

**Comment by ogrotten** [comment]
Just to be clear, this feature allows user-specific permissions?

That is to say
* "username ogrotten has access to X page" 
* "username tjwebb does not have access to Y page"

and this is in addition to the current way which is "role moderator can access this group of pages"

Is this correct?

Can anyone offer any details?

**Comment by tjwebb** [comment]
Yep, it allows you to connect users directly to permissions. Weve reviewed
this PR and plan to merge it in once we've completed some other
improvements that are currently in progress. ETA is 5-7 days.

**Comment by tjwebb** [comment]
hey @anthonybriand I haven't forgotten about this. I'm going to merge it in for 1.2.0

**Comment by anthonybriand** [comment]
Ok no problems :)

**Comment by anthonybriand** [comment]
@tjwebb I have updated my fork to match the criteria system

**Pull request merged**
