### PR TITLE
support custom actions and controllers

### LINKED ISSUE #20: make installable hook
http://sailsjs.org/#!/documentation/concepts/extending-sails/Hooks/installablehooks.html

### LINKED ISSUE #21: Custom actions
One thing that may be blocking for some people is that the actions that may be protected by this is limited to CRUD actions. How difficult would it be to allow custom actions to be defined, so that for example, a `User` could be given permission to execute a `run` action on a given `Task`?

### PR DESCRIPTION
**Pull request by tjwebb**
- resolves #20
- resolves #21

### CODE REVIEW

**Comment by Benew** [comment]
Hi! Nice PR! How long before a merge?

**Comment by tjwebb** [comment]
Hi @Benew , I'll try to merge this week.

**Comment by jaime-franco** [comment]
There is a way to create custom actions validation rules? or this still on progress?

**Comment by Cornik34** [comment]
Any news on this feature?

**Pull request closed without merging**
